version: '3'
services:
  tp-analysis:
    image: transport-performance:latest
    environment:
      - CONFIG_FILE=${CONFIG_FILE:-default_config.toml}
      - COUNTRY_NAME=${COUNTRY_NAME:-None}
      - AREA_NAME=${AREA_NAME:-None}
      - BBOX=${BBOX:-None}
      - BBOX_CRS=${BBOX_CRS:-EPSG:4326}
      - CENTRE=${CENTRE:-None}
      - CENTRE_CRS=${CENTRE_CRS:-EPSG:4326}
      - BUFFER_ESTIMATION_CRS=${BUFFER_ESTIMATION_CRS:-EPSG:27700}
      - EMPTY_FEED=${EMPTY_FEED:-0}
      - FAST_TRAVEL=${FAST_TRAVEL:-1}
      - CALCULATE_SUMMARIES=${CALCULATE_SUMMARIES:-1}
      - BATCH_ORIG=${BATCH_ORIG:-0}
      - GTFS_OSM_SUBDIR=${GTFS_OSM_SUBDIR:-None}
    volumes:
      - ./data:/analysis/data/
